#!/usr/bin/env bash
#
# Adds the BongoCat pacman repository to this machine.
#
#   curl -fsSL __SITE_URL__/setup.sh | sudo bash
#
# The placeholders in this file are filled in when the site is deployed, so the
# script always trusts the key that actually signed the repository, and nothing
# else.

set -euo pipefail

readonly SITE_URL='__SITE_URL__'
readonly REPO_NAME='__REPO_NAME__'
readonly FINGERPRINT='__FINGERPRINT_COMPACT__'
readonly PACMAN_CONF=/etc/pacman.conf
readonly KEYRING_TMP=$(mktemp)

cleanup() { rm -f "$KEYRING_TMP"; }
trap cleanup EXIT

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }

(( EUID == 0 )) || die 'run this script as root (curl ... | sudo bash)'
# Matches only a deployed copy: the template placeholder does not look like a URL.
[[ $SITE_URL =~ ^https?://[^/]+$ ]] || die 'this script was not generated by a deployment'
command -v pacman-key >/dev/null 2>&1 || die 'pacman-key not found: this is not an Arch Linux system'

info "fetching the repository signing key"
curl -fsSL "$SITE_URL/$REPO_NAME-repo.asc" -o "$KEYRING_TMP" \
  || die "cannot download $SITE_URL/$REPO_NAME-repo.asc"

# Trust is anchored on the fingerprint that was baked in at deployment time.
actual=$(gpg --with-colons --import-options show-only --import "$KEYRING_TMP" 2>/dev/null \
  | awk -F: '/^fpr:/ { print toupper($10); exit }')
[[ -n $actual ]] || die 'the downloaded file is not an OpenPGP public key'
if [[ ${actual// /} != "${FINGERPRINT// /}" ]]; then
  die "fingerprint mismatch: expected ${FINGERPRINT// /}, got ${actual// /}"
fi

info "adding $actual to the pacman keyring"
pacman-key --add "$KEYRING_TMP" >/dev/null
pacman-key --lsign-key "$actual" >/dev/null

if grep -qE "^\[$REPO_NAME\]$" "$PACMAN_CONF"; then
  info "[$REPO_NAME] is already configured in $PACMAN_CONF"
else
  info "adding [$REPO_NAME] to $PACMAN_CONF"
  cp -a "$PACMAN_CONF" "$PACMAN_CONF.bak.$(date +%Y%m%d%H%M%S)"
  cat >>"$PACMAN_CONF" <<EOF

[$REPO_NAME]
SigLevel = Required DatabaseOptional
Server = $SITE_URL/\$arch
EOF
fi

info 'refreshing the package databases'
pacman -Sy

cat <<EOF

Done. The repository is configured, install the pet with:

    sudo pacman -S $REPO_NAME

Keep the system updated with "sudo pacman -Syu" before installing: the packages
are built on a rolling release, so they may expect slightly newer libraries than
an outdated system provides.
EOF
